### ISSUE TITLE
Send failure notification to Primero case if upsert failed

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#19]
## Background, context, and business value

When we fail to upsert a Primero case with the [upsertCases](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js) job and get an error back from Primero, we want to launch a failure flow job to send a `failed` status message to the Primero record.

I've created a [new job](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1d-sendPrimeroFailureStatus.js) for this based on the existing failure job that runs in case the [HIS request](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1-getPatientData.js) failed.

However, the new job doesn't seem to have access to the case details in state, see run log [here](https://www.openfn.org/projects/p5kaap/runs/rg5b3eym).

## The specific request, in as few words as possible

When [upsertCases job](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js) fails, we want to run a [new job](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1d-sendPrimeroFailureStatus.js) that sends a `failed` status to the record that we failed to update.

## state.json

For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpoint14April.json)

See new job set up on the [platform](https://www.openfn.org/projects/p5kaap/jobs/jyd9xa)

## adaptor
1. `language-http` to connect to HIS API
2. `language-primero` to connect to Primero v2 API

**Comment by taylordowns2000** [comment]
This looks good to go. (Please read through my last 4 commits. Have kept each separate and tried to make them as clear and self-explanatory as possible.) Note that I've added the recommended logs so that whenever testing is possible (no more timeouts on the prior job, see below*) you should be able to make final adjustments instantaneously.

*The below: https://www.openfn.org/projects/p5kaap/jobs/jv7r65 - this job, however, seems to be dying with an exit code `4`—not a normal timeout, but something unresponsive. Any ideas on why?

**UPDATE** -- oops, looks like Zenhub doesn't link commits the way github does! my bad. here's the list of the commits:

1. https://github.com/OpenFn/primero-thailand/commit/f4a03a812dd9ff9ce1c5e54a315e33eecec10781
2. https://github.com/OpenFn/primero-thailand/commit/81af7dedffa26967ff783a858376d95accb29d09
3. https://github.com/OpenFn/primero-thailand/commit/f92cfb15b6e7212c542c2e422539b50feafa1b6b
4. https://github.com/OpenFn/primero-thailand/commit/f9866da520f95e54a538620efc9b2f023b4cd049

cc @lakhassane , please see `#1` above as a reminder of the style we're going for :mechanical_arm:

**Comment by ritazagoni** [comment]
@taylordowns2000 The job fails with a `data is not defined` error, see run https://www.openfn.org/projects/p5kaap/runs/rg569r97

I also see that in the upsert we're sending `"mark_synced_status": "synced"`. We are supposed to send `"mark_synced_status": "failed"`.

**Comment by ritazagoni** [comment]
over to @lakhassane

**Comment by lakhassane** [comment]
solve with last commit: https://www.openfn.org/projects/p5kaap/runs/rmknadgd
